# Generated by Django 4.0.4 on 2022-06-01 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_collection_order_product_collectoin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='collectoin',
            new_name='collection',
        ),
    ]
